# Generated by Django 5.2.3 on 2025-06-29 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DokterGigi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('spesialis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('alamat', models.TextField()),
                ('no_hp', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TindakanGigi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tindakan', models.CharField(max_length=100)),
                ('biaya', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RekamMedisGigi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keluhan', models.TextField()),
                ('tanggal_periksa', models.DateField(auto_now_add=True)),
                ('catatan', models.TextField()),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doktergigi')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pasien')),
                ('tindakan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tindakangigi')),
            ],
        ),
    ]
